version: "3.8"
services:
  api:
    build: .
    command: 
    - bash
    - -c
    - |
      wait-for-it --service db:3306 --timeout=60
      uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
    - 8000:80
    environment:
      DB_URI : mysql+pymysql://root:root@db:3306/chatApp 
    volumes:
    - ./chatapp:/app/chatapp
    depends_on:
    - db

  db:
    image: mysql:8.1
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}

    volumes:
    - ./db:/var/lib/mysql
