version: "3.8"
services:
  api:
    build: .
    command: 
    - bash
    - -c
    - |
      wait-for-it --service db:3306 --timeout=60
      alembic upgrade head
      uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
    - 8000:80
    environment:
      DB_HOST               : ${DB_HOST}
      DB_NAME               : ${DB_NAME}
      DB_USER               : ${DB_USER}
      DB_PASS               : ${DB_PASS}
      DB_URI                : ${DB_URI}
    volumes:
    - ./chatapp:/app/chatapp
    - ./alembic:/app/alembic
    depends_on:
    - db

  db:
    image: mysql:8.1
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}

    volumes:
    - ./db:/var/lib/mysql
