"""Add profile_photo_path column

Revision ID: 1ab2c4e9a361
Revises: 63a84f5093fa
Create Date: 2023-10-23 23:57:44.539693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab2c4e9a361'
down_revision: Union[str, None] = '63a84f5093fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_photo_path')
    # ### end Alembic commands ###
