"""Initial Migration

Revision ID: 54187334b424
Revises: 94cf2b90d3fd
Create Date: 2023-09-25 21:31:12.821360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54187334b424'
down_revision: Union[str, None] = '94cf2b90d3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_friend_combination', 'friendship', ['user_id', 'friend_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_friend_combination', 'friendship', type_='unique')
    # ### end Alembic commands ###
