"""Add is_read column to Message

Revision ID: b8ceb2e3c558
Revises: 89e44f74ee51
Create Date: 2023-09-29 21:51:46.074543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ceb2e3c558'
down_revision: Union[str, None] = '89e44f74ee51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
