"""Add is_read column to friendship

Revision ID: c99f84377731
Revises: b8ceb2e3c558
Create Date: 2023-10-01 19:30:55.360499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99f84377731'
down_revision: Union[str, None] = 'b8ceb2e3c558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship', sa.Column('is_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendship', 'is_read')
    # ### end Alembic commands ###
