"""Initial migration 3

Revision ID: f9a587b9bf50
Revises: a2f8fc2567f7
Create Date: 2023-08-26 00:42:22.782147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a587b9bf50'
down_revision: Union[str, None] = 'a2f8fc2567f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
