name: Deploy

on: [push]

jobs:
  dpeloy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build API Image
        run: docker build . --file Dockerfile --tag ghcr.io/aymaneboukrouh/chatapp-api:latest
      
      - name: Log In to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push API Image to GitHub Container Registry
        run: docker push ghcr.io/aymaneboukrouh/chatapp-api:latest
