name: Deploy

on: [push]

jobs:
  dpeloy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log In to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build API Image
        run: docker build . --file Dockerfile --tag ghcr.io/aymaneboukrouh/chatapp-api:latest

      - name: Push API Image to GitHub Container Registry
        run: docker push ghcr.io/aymaneboukrouh/chatapp-api:latest
